// Code generated by protoc-gen-go. DO NOT EDIT.
// source: public.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 消息ID定义规范  消息ID必须在65535以下   0~30000由C#层和战斗服务器交互以及服务器内部使用, 其中28001~30000是战斗链接流程消息，30001~35000由Lua逻辑与服务器交互
// 注意消息ID不要与其他消息ID文件重复
type MSGID int32

const (
	MSGID_Undefine_         MSGID = 0
	MSGID_ReqGateWayClientE MSGID = 1
	MSGID_ResGateWayClientE MSGID = 2
	// 心跳
	MSGID_ReqHeartbeatE   MSGID = 1001
	MSGID_ResHeartbeatE   MSGID = 1002
	MSGID_ReqLoginE       MSGID = 1003
	MSGID_ResLoginE       MSGID = 1004
	MSGID_ReqChatE        MSGID = 1005
	MSGID_ResChatE        MSGID = 1006
	MSGID_ResHistoryChatE MSGID = 1007
	MSGID_MAX_COUNT       MSGID = 65536
)

var MSGID_name = map[int32]string{
	0:     "Undefine_",
	1:     "ReqGateWayClientE",
	2:     "ResGateWayClientE",
	1001:  "ReqHeartbeatE",
	1002:  "ResHeartbeatE",
	1003:  "ReqLoginE",
	1004:  "ResLoginE",
	1005:  "ReqChatE",
	1006:  "ResChatE",
	1007:  "ResHistoryChatE",
	65536: "MAX_COUNT",
}
var MSGID_value = map[string]int32{
	"Undefine_":         0,
	"ReqGateWayClientE": 1,
	"ResGateWayClientE": 2,
	"ReqHeartbeatE":     1001,
	"ResHeartbeatE":     1002,
	"ReqLoginE":         1003,
	"ResLoginE":         1004,
	"ReqChatE":          1005,
	"ResChatE":          1006,
	"ResHistoryChatE":   1007,
	"MAX_COUNT":         65536,
}

func (x MSGID) String() string {
	return proto.EnumName(MSGID_name, int32(x))
}
func (MSGID) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

type MSDTYPE int32

const (
	MSDTYPE_Heart  MSDTYPE = 0
	MSDTYPE_Gate   MSDTYPE = 1001
	MSDTYPE_Hall   MSDTYPE = 2001
	MSDTYPE_Earth  MSDTYPE = 3001
	MSDTYPE_Battle MSDTYPE = 3002
	MSDTYPE_Login  MSDTYPE = 8001
)

var MSDTYPE_name = map[int32]string{
	0:    "Heart",
	1001: "Gate",
	2001: "Hall",
	3001: "Earth",
	3002: "Battle",
	8001: "Login",
}
var MSDTYPE_value = map[string]int32{
	"Heart":  0,
	"Gate":   1001,
	"Hall":   2001,
	"Earth":  3001,
	"Battle": 3002,
	"Login":  8001,
}

func (x MSDTYPE) String() string {
	return proto.EnumName(MSDTYPE_name, int32(x))
}
func (MSDTYPE) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

type ResLogin_Result int32

const (
	ResLogin_unknown ResLogin_Result = 0
	ResLogin_success ResLogin_Result = 1
	ResLogin_fail    ResLogin_Result = 2
)

var ResLogin_Result_name = map[int32]string{
	0: "unknown",
	1: "success",
	2: "fail",
}
var ResLogin_Result_value = map[string]int32{
	"unknown": 0,
	"success": 1,
	"fail":    2,
}

func (x ResLogin_Result) String() string {
	return proto.EnumName(ResLogin_Result_name, int32(x))
}
func (ResLogin_Result) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{5, 0} }

type ReqHeartbeat struct {
	Uid int64 `protobuf:"varint,1,opt,name=uid" json:"uid"`
}

func (m *ReqHeartbeat) Reset()                    { *m = ReqHeartbeat{} }
func (m *ReqHeartbeat) String() string            { return proto.CompactTextString(m) }
func (*ReqHeartbeat) ProtoMessage()               {}
func (*ReqHeartbeat) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *ReqHeartbeat) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type ResHeartbeat struct {
	Uid            int64 `protobuf:"varint,1,opt,name=uid" json:"uid"`
	ServerUnixTime int64 `protobuf:"varint,2,opt,name=serverUnixTime" json:"serverUnixTime"`
}

func (m *ResHeartbeat) Reset()                    { *m = ResHeartbeat{} }
func (m *ResHeartbeat) String() string            { return proto.CompactTextString(m) }
func (*ResHeartbeat) ProtoMessage()               {}
func (*ResHeartbeat) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *ResHeartbeat) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *ResHeartbeat) GetServerUnixTime() int64 {
	if m != nil {
		return m.ServerUnixTime
	}
	return 0
}

type Chat struct {
	Name    string `protobuf:"bytes,1,opt,name=name" json:"name"`
	Content string `protobuf:"bytes,2,opt,name=content" json:"content"`
}

func (m *Chat) Reset()                    { *m = Chat{} }
func (m *Chat) String() string            { return proto.CompactTextString(m) }
func (*Chat) ProtoMessage()               {}
func (*Chat) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *Chat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Chat) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type HistroyChat struct {
	History []*Chat `protobuf:"bytes,1,rep,name=history" json:"history"`
}

func (m *HistroyChat) Reset()                    { *m = HistroyChat{} }
func (m *HistroyChat) String() string            { return proto.CompactTextString(m) }
func (*HistroyChat) ProtoMessage()               {}
func (*HistroyChat) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{3} }

func (m *HistroyChat) GetHistory() []*Chat {
	if m != nil {
		return m.History
	}
	return nil
}

type ReqLogin struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name"`
	RoomId int32  `protobuf:"varint,2,opt,name=roomId" json:"roomId"`
	UserId int64  `protobuf:"varint,3,opt,name=userId" json:"userId"`
}

func (m *ReqLogin) Reset()                    { *m = ReqLogin{} }
func (m *ReqLogin) String() string            { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()               {}
func (*ReqLogin) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{4} }

func (m *ReqLogin) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqLogin) GetRoomId() int32 {
	if m != nil {
		return m.RoomId
	}
	return 0
}

func (m *ReqLogin) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ResLogin struct {
	Result ResLogin_Result `protobuf:"varint,1,opt,name=result,enum=Message.ResLogin_Result" json:"result"`
}

func (m *ResLogin) Reset()                    { *m = ResLogin{} }
func (m *ResLogin) String() string            { return proto.CompactTextString(m) }
func (*ResLogin) ProtoMessage()               {}
func (*ResLogin) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{5} }

func (m *ResLogin) GetResult() ResLogin_Result {
	if m != nil {
		return m.Result
	}
	return ResLogin_unknown
}

func init() {
	proto.RegisterType((*ReqHeartbeat)(nil), "Message.ReqHeartbeat")
	proto.RegisterType((*ResHeartbeat)(nil), "Message.ResHeartbeat")
	proto.RegisterType((*Chat)(nil), "Message.Chat")
	proto.RegisterType((*HistroyChat)(nil), "Message.HistroyChat")
	proto.RegisterType((*ReqLogin)(nil), "Message.ReqLogin")
	proto.RegisterType((*ResLogin)(nil), "Message.ResLogin")
	proto.RegisterEnum("Message.MSGID", MSGID_name, MSGID_value)
	proto.RegisterEnum("Message.MSDTYPE", MSDTYPE_name, MSDTYPE_value)
	proto.RegisterEnum("Message.ResLogin_Result", ResLogin_Result_name, ResLogin_Result_value)
}

func init() { proto.RegisterFile("public.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 483 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x14, 0xac, 0x13, 0x27, 0x5b, 0xbf, 0x34, 0xc9, 0xf2, 0x04, 0xd4, 0xc7, 0xc8, 0x07, 0xa8, 0x2a,
	0x14, 0xa1, 0x82, 0x38, 0x22, 0xd1, 0xd4, 0x6a, 0x22, 0x91, 0x16, 0xb9, 0x89, 0xf8, 0xb8, 0x54,
	0x9b, 0xe4, 0xb5, 0x31, 0x38, 0xeb, 0xc6, 0xbb, 0x06, 0x72, 0xeb, 0xdf, 0x82, 0x1b, 0x3f, 0xa1,
	0x3f, 0x83, 0xef, 0xbf, 0x80, 0x76, 0xed, 0xa0, 0xaa, 0x42, 0xdc, 0xde, 0xcc, 0x9b, 0x9d, 0x9d,
	0x1d, 0x1b, 0xb6, 0x2e, 0xf2, 0x49, 0x12, 0x4f, 0xbb, 0x17, 0x59, 0xaa, 0x53, 0x64, 0x43, 0x52,
	0x4a, 0x9c, 0x53, 0xd0, 0x81, 0xad, 0x88, 0x96, 0x7d, 0x12, 0x99, 0x9e, 0x90, 0xd0, 0xc8, 0xa1,
	0x9a, 0xc7, 0x33, 0xdf, 0xe9, 0x38, 0x3b, 0xd5, 0xc8, 0x8c, 0x41, 0xdf, 0x28, 0xd4, 0x7f, 0x14,
	0x78, 0x0f, 0x5a, 0x8a, 0xb2, 0xf7, 0x94, 0x8d, 0x65, 0xfc, 0x71, 0x14, 0x2f, 0xc8, 0xaf, 0xd8,
	0xe5, 0x0d, 0x36, 0x78, 0x0c, 0x6e, 0x6f, 0x2e, 0x34, 0x22, 0xb8, 0x52, 0x2c, 0xc8, 0x5a, 0x78,
	0x91, 0x9d, 0xd1, 0x07, 0x36, 0x4d, 0xa5, 0x26, 0xa9, 0xed, 0x61, 0x2f, 0x5a, 0xc3, 0xe0, 0x09,
	0x34, 0xfa, 0xb1, 0xd2, 0x59, 0xba, 0xb2, 0x87, 0xef, 0x03, 0x9b, 0xc7, 0x4a, 0xa7, 0xd9, 0xca,
	0x77, 0x3a, 0xd5, 0x9d, 0xc6, 0x5e, 0xb3, 0x5b, 0xbe, 0xa5, 0x6b, 0xf6, 0xd1, 0x7a, 0x1b, 0x1c,
	0xc1, 0x66, 0x44, 0xcb, 0xe7, 0xe9, 0x79, 0x2c, 0xff, 0x79, 0xe3, 0x5d, 0xa8, 0x67, 0x69, 0xba,
	0x18, 0xcc, 0xec, 0x85, 0xb5, 0xa8, 0x44, 0x86, 0xcf, 0x15, 0x65, 0x83, 0x99, 0x5f, 0xb5, 0xaf,
	0x28, 0x51, 0xf0, 0xd6, 0xf8, 0xa9, 0xc2, 0xef, 0x21, 0xd4, 0x33, 0x52, 0x79, 0xa2, 0xad, 0x63,
	0x6b, 0xcf, 0xff, 0x9b, 0x61, 0x2d, 0x31, 0x43, 0x9e, 0xe8, 0xa8, 0xd4, 0x05, 0x0f, 0xa0, 0x5e,
	0x30, 0xd8, 0x00, 0x96, 0xcb, 0x77, 0x32, 0xfd, 0x20, 0xf9, 0x86, 0x01, 0x2a, 0x9f, 0x4e, 0x49,
	0x29, 0xee, 0xe0, 0x26, 0xb8, 0x67, 0x22, 0x4e, 0x78, 0x65, 0xf7, 0xca, 0x81, 0xda, 0xf0, 0xe4,
	0x70, 0x70, 0x80, 0x4d, 0xf0, 0xc6, 0x72, 0x46, 0x67, 0xb1, 0xa4, 0x53, 0xbe, 0x81, 0x77, 0xe0,
	0x56, 0x44, 0xcb, 0x43, 0xa1, 0xe9, 0xa5, 0x58, 0xf5, 0x92, 0x98, 0xa4, 0x0e, 0xb9, 0x53, 0xd0,
	0xea, 0x06, 0x5d, 0x41, 0x84, 0xe6, 0xf5, 0x8f, 0x1b, 0xf2, 0xaf, 0xac, 0xe0, 0xd4, 0x35, 0xee,
	0x1b, 0xc3, 0x16, 0x78, 0xeb, 0xaa, 0x42, 0xfe, 0xbd, 0xc4, 0xaa, 0xc4, 0x3f, 0x18, 0x36, 0x6d,
	0x95, 0xa6, 0xde, 0x90, 0xff, 0x2c, 0xa1, 0x2a, 0xe0, 0x2f, 0x86, 0xb7, 0xa1, 0x6d, 0x1c, 0x8b,
	0xda, 0x0b, 0xf6, 0x37, 0xc3, 0x36, 0x78, 0xc3, 0x67, 0xaf, 0x4e, 0x7b, 0xc7, 0xe3, 0xa3, 0x11,
	0xbf, 0xbc, 0x74, 0x77, 0x8f, 0x81, 0x0d, 0x4f, 0x0e, 0x46, 0xaf, 0x5f, 0x84, 0xe8, 0x41, 0xcd,
	0x06, 0xe0, 0x1b, 0xe8, 0x81, 0x6b, 0x62, 0x9b, 0x64, 0x1e, 0xb8, 0x7d, 0x91, 0x24, 0xfc, 0xaa,
	0x8d, 0x00, 0xb5, 0x50, 0x64, 0x7a, 0xce, 0x3f, 0x6d, 0x63, 0x03, 0xea, 0xfb, 0x42, 0xeb, 0x84,
	0xf8, 0xe7, 0x6d, 0xb3, 0xb0, 0xb1, 0xf8, 0x97, 0xa7, 0xfb, 0xde, 0x1b, 0xb6, 0x28, 0x5a, 0x9f,
	0xd4, 0xed, 0x5f, 0xfd, 0xe8, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x80, 0xb3, 0xd9, 0xe5,
	0x02, 0x00, 0x00,
}
